// Auto-generated by tools/build-fingering-data.mjs from 01 Source/음별_20/*.svg.
// Do not edit note data by hand.

export const DETECTABLE_HOLES = [
  "L2",
  "L3",
  "L4",
  "L5",
  "R2",
  "R3",
  "R4",
  "R5"
];

export const NOTE_ORDER = [
  "lowLa",
  "lowLaS",
  "lowSi",
  "do",
  "doS",
  "re",
  "reS",
  "mi",
  "fa",
  "faS",
  "sol",
  "solS",
  "la",
  "laS",
  "si",
  "highDo",
  "highDoS",
  "highRe",
  "highReS",
  "highMi"
];

export const NOTE_LABELS_KO = {
  "lowLa": "낮은 라",
  "lowLaS": "낮은 라#",
  "lowSi": "낮은 시",
  "do": "도",
  "doS": "도#",
  "re": "레",
  "reS": "레#",
  "mi": "미",
  "fa": "파",
  "faS": "파#",
  "sol": "솔",
  "solS": "솔#",
  "la": "라",
  "laS": "라#",
  "si": "시",
  "highDo": "높은 도",
  "highDoS": "높은 도#",
  "highRe": "높은 레",
  "highReS": "높은 레#",
  "highMi": "높은 미"
};

export const FINGER_LABELS_KO = {
  "L1": "왼손 엄지",
  "L2": "왼손 검지",
  "L3": "왼손 중지",
  "L4": "왼손 약지",
  "L5": "왼손 새끼",
  "LS": "왼손 보조구멍",
  "R1": "오른손 엄지",
  "R2": "오른손 검지",
  "R3": "오른손 중지",
  "R4": "오른손 약지",
  "R5": "오른손 새끼",
  "RS": "오른손 보조구멍"
};

export const HOLES_12 = [
  {
    "id": "L5",
    "finger": "왼손 새끼",
    "side": "front",
    "cx": 228,
    "cy": 150,
    "r": 13,
    "detectable": true
  },
  {
    "id": "L4",
    "finger": "왼손 약지",
    "side": "front",
    "cx": 315,
    "cy": 126,
    "r": 17,
    "detectable": true
  },
  {
    "id": "L3",
    "finger": "왼손 중지",
    "side": "front",
    "cx": 402,
    "cy": 114,
    "r": 19,
    "detectable": true
  },
  {
    "id": "L2",
    "finger": "왼손 검지",
    "side": "front",
    "cx": 487,
    "cy": 118,
    "r": 18,
    "detectable": true
  },
  {
    "id": "LS",
    "finger": "왼손 보조구멍",
    "side": "front",
    "cx": 516,
    "cy": 166,
    "r": 8,
    "detectable": false
  },
  {
    "id": "R2",
    "finger": "오른손 검지",
    "side": "front",
    "cx": 582,
    "cy": 178,
    "r": 19,
    "detectable": true
  },
  {
    "id": "R3",
    "finger": "오른손 중지",
    "side": "front",
    "cx": 660,
    "cy": 190,
    "r": 18,
    "detectable": true
  },
  {
    "id": "R4",
    "finger": "오른손 약지",
    "side": "front",
    "cx": 732,
    "cy": 200,
    "r": 15,
    "detectable": true
  },
  {
    "id": "R5",
    "finger": "오른손 새끼",
    "side": "front",
    "cx": 796,
    "cy": 206,
    "r": 13,
    "detectable": true
  },
  {
    "id": "RS",
    "finger": "오른손 보조구멍",
    "side": "front",
    "cx": 765,
    "cy": 242,
    "r": 8,
    "detectable": false
  },
  {
    "id": "R1",
    "finger": "오른손 엄지",
    "side": "back",
    "cx": 360,
    "cy": 224,
    "r": 19,
    "detectable": false
  },
  {
    "id": "L1",
    "finger": "왼손 엄지",
    "side": "back",
    "cx": 606,
    "cy": 172,
    "r": 21,
    "detectable": false
  }
];

export const NOTES_12 = [
  {
    "id": "lowLa",
    "solfege": "낮은 라",
    "label": "낮은 라",
    "pitch": "A4",
    "midi": 69,
    "breath": 1,
    "holes": {
      "L5": 1,
      "L4": 1,
      "L3": 1,
      "L2": 1,
      "LS": 1,
      "R2": 1,
      "R3": 1,
      "R4": 1,
      "R5": 1,
      "RS": 1,
      "R1": 1,
      "L1": 1
    },
    "detectable": {
      "L2": 1,
      "L3": 1,
      "L4": 1,
      "L5": 1,
      "R2": 1,
      "R3": 1,
      "R4": 1,
      "R5": 1
    },
    "tip": "12개 구멍을 모두 막고 입김은 가장 여리게.",
    "flags": [],
    "ambiguousWith": [
      "lowLaS"
    ]
  },
  {
    "id": "lowLaS",
    "solfege": "낮은 라♯·시♭",
    "label": "낮은 라#",
    "pitch": "A#4/Bb4",
    "midi": 70,
    "breath": 1,
    "holes": {
      "L5": 1,
      "L4": 1,
      "L3": 1,
      "L2": 1,
      "LS": 1,
      "R2": 1,
      "R3": 1,
      "R4": 1,
      "R5": 1,
      "RS": 0,
      "R1": 1,
      "L1": 1
    },
    "detectable": {
      "L2": 1,
      "L3": 1,
      "L4": 1,
      "L5": 1,
      "R2": 1,
      "R3": 1,
      "R4": 1,
      "R5": 1
    },
    "tip": "낮은 라에서 오른손 보조구멍(RS)만 엽니다.",
    "flags": [
      "교차운지"
    ],
    "ambiguousWith": [
      "lowLa"
    ]
  },
  {
    "id": "lowSi",
    "solfege": "낮은 시",
    "label": "낮은 시",
    "pitch": "B4",
    "midi": 71,
    "breath": 1,
    "holes": {
      "L5": 1,
      "L4": 1,
      "L3": 1,
      "L2": 1,
      "LS": 1,
      "R2": 1,
      "R3": 1,
      "R4": 1,
      "R5": 0,
      "RS": 0,
      "R1": 1,
      "L1": 1
    },
    "detectable": {
      "L2": 1,
      "L3": 1,
      "L4": 1,
      "L5": 1,
      "R2": 1,
      "R3": 1,
      "R4": 1,
      "R5": 0
    },
    "tip": "오른손 새끼(R5)와 보조구멍(RS)을 엽니다.",
    "flags": []
  },
  {
    "id": "do",
    "solfege": "도",
    "label": "도",
    "pitch": "C5",
    "midi": 72,
    "breath": 2,
    "holes": {
      "L5": 1,
      "L4": 1,
      "L3": 1,
      "L2": 1,
      "LS": 1,
      "R2": 1,
      "R3": 1,
      "R4": 0,
      "R5": 0,
      "RS": 0,
      "R1": 1,
      "L1": 1
    },
    "detectable": {
      "L2": 1,
      "L3": 1,
      "L4": 1,
      "L5": 1,
      "R2": 1,
      "R3": 1,
      "R4": 0,
      "R5": 0
    },
    "tip": "오른손 약지(R4)까지 엽니다. 기준이 되는 음.",
    "flags": []
  },
  {
    "id": "doS",
    "solfege": "도♯·레♭",
    "label": "도#",
    "pitch": "C#5/Db5",
    "midi": 73,
    "breath": 2,
    "holes": {
      "L5": 1,
      "L4": 1,
      "L3": 1,
      "L2": 1,
      "LS": 1,
      "R2": 1,
      "R3": 0,
      "R4": 1,
      "R5": 0,
      "RS": 0,
      "R1": 1,
      "L1": 1
    },
    "detectable": {
      "L2": 1,
      "L3": 1,
      "L4": 1,
      "L5": 1,
      "R2": 1,
      "R3": 0,
      "R4": 1,
      "R5": 0
    },
    "tip": "교차운지: 약지(R4)는 막고 중지(R3)를 엽니다.",
    "flags": [
      "교차운지"
    ]
  },
  {
    "id": "re",
    "solfege": "레",
    "label": "레",
    "pitch": "D5",
    "midi": 74,
    "breath": 2,
    "holes": {
      "L5": 1,
      "L4": 1,
      "L3": 1,
      "L2": 1,
      "LS": 1,
      "R2": 1,
      "R3": 0,
      "R4": 0,
      "R5": 0,
      "RS": 0,
      "R1": 1,
      "L1": 1
    },
    "detectable": {
      "L2": 1,
      "L3": 1,
      "L4": 1,
      "L5": 1,
      "R2": 1,
      "R3": 0,
      "R4": 0,
      "R5": 0
    },
    "tip": "오른손은 검지(R2)만 남기고 엽니다.",
    "flags": []
  },
  {
    "id": "reS",
    "solfege": "레♯·미♭",
    "label": "레#",
    "pitch": "D#5/Eb5",
    "midi": 75,
    "breath": 2,
    "holes": {
      "L5": 1,
      "L4": 1,
      "L3": 1,
      "L2": 1,
      "LS": 1,
      "R2": 0,
      "R3": 0,
      "R4": 1,
      "R5": 0,
      "RS": 0,
      "R1": 1,
      "L1": 1
    },
    "detectable": {
      "L2": 1,
      "L3": 1,
      "L4": 1,
      "L5": 1,
      "R2": 0,
      "R3": 0,
      "R4": 1,
      "R5": 0
    },
    "tip": "교차운지: 오른손 약지(R4)만 막습니다.",
    "flags": [
      "교차운지"
    ]
  },
  {
    "id": "mi",
    "solfege": "미",
    "label": "미",
    "pitch": "E5",
    "midi": 76,
    "breath": 2,
    "holes": {
      "L5": 1,
      "L4": 1,
      "L3": 1,
      "L2": 1,
      "LS": 1,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0,
      "RS": 0,
      "R1": 1,
      "L1": 1
    },
    "detectable": {
      "L2": 1,
      "L3": 1,
      "L4": 1,
      "L5": 1,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0
    },
    "tip": "오른손 전체를 엽니다. 오른손 졸업!",
    "flags": []
  },
  {
    "id": "fa",
    "solfege": "파",
    "label": "파",
    "pitch": "F5",
    "midi": 77,
    "breath": 3,
    "holes": {
      "L5": 0,
      "L4": 1,
      "L3": 1,
      "L2": 1,
      "LS": 1,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0,
      "RS": 0,
      "R1": 1,
      "L1": 1
    },
    "detectable": {
      "L2": 1,
      "L3": 1,
      "L4": 1,
      "L5": 0,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0
    },
    "tip": "왼손 새끼(L5)를 엽니다.",
    "flags": []
  },
  {
    "id": "faS",
    "solfege": "파♯·솔♭",
    "label": "파#",
    "pitch": "F#5/Gb5",
    "midi": 78,
    "breath": 3,
    "holes": {
      "L5": 1,
      "L4": 0,
      "L3": 1,
      "L2": 1,
      "LS": 1,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0,
      "RS": 0,
      "R1": 1,
      "L1": 1
    },
    "detectable": {
      "L2": 1,
      "L3": 1,
      "L4": 0,
      "L5": 1,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0
    },
    "tip": "교차운지: 왼손 새끼(L5)를 막고 약지(L4)를 엽니다.",
    "flags": [
      "교차운지"
    ]
  },
  {
    "id": "sol",
    "solfege": "솔",
    "label": "솔",
    "pitch": "G5",
    "midi": 79,
    "breath": 3,
    "holes": {
      "L5": 0,
      "L4": 0,
      "L3": 1,
      "L2": 1,
      "LS": 1,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0,
      "RS": 0,
      "R1": 1,
      "L1": 1
    },
    "detectable": {
      "L2": 1,
      "L3": 1,
      "L4": 0,
      "L5": 0,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0
    },
    "tip": "왼손 약지(L4)까지 엽니다.",
    "flags": []
  },
  {
    "id": "solS",
    "solfege": "솔♯·라♭",
    "label": "솔#",
    "pitch": "G#5/Ab5",
    "midi": 80,
    "breath": 3,
    "holes": {
      "L5": 1,
      "L4": 0,
      "L3": 0,
      "L2": 1,
      "LS": 1,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0,
      "RS": 0,
      "R1": 1,
      "L1": 1
    },
    "detectable": {
      "L2": 1,
      "L3": 0,
      "L4": 0,
      "L5": 1,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0
    },
    "tip": "교차운지: 새끼(L5)를 다시 막고 중지(L3)를 엽니다.",
    "flags": [
      "교차운지"
    ]
  },
  {
    "id": "la",
    "solfege": "라",
    "label": "라",
    "pitch": "A5",
    "midi": 81,
    "breath": 3,
    "holes": {
      "L5": 0,
      "L4": 0,
      "L3": 0,
      "L2": 1,
      "LS": 1,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0,
      "RS": 0,
      "R1": 1,
      "L1": 1
    },
    "detectable": {
      "L2": 1,
      "L3": 0,
      "L4": 0,
      "L5": 0,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0
    },
    "tip": "왼손은 검지(L2)와 보조구멍만 남습니다.",
    "flags": []
  },
  {
    "id": "laS",
    "solfege": "라♯·시♭",
    "label": "라#",
    "pitch": "A#5/Bb5",
    "midi": 82,
    "breath": 4,
    "holes": {
      "L5": 1,
      "L4": 0,
      "L3": 0,
      "L2": 0,
      "LS": 0,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0,
      "RS": 0,
      "R1": 1,
      "L1": 1
    },
    "detectable": {
      "L2": 0,
      "L3": 0,
      "L4": 0,
      "L5": 1,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0
    },
    "tip": "교차운지: 왼손 새끼(L5)만 막습니다.",
    "flags": [
      "교차운지"
    ]
  },
  {
    "id": "si",
    "solfege": "시",
    "label": "시",
    "pitch": "B5",
    "midi": 83,
    "breath": 4,
    "holes": {
      "L5": 0,
      "L4": 0,
      "L3": 0,
      "L2": 0,
      "LS": 0,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0,
      "RS": 0,
      "R1": 1,
      "L1": 1
    },
    "detectable": {
      "L2": 0,
      "L3": 0,
      "L4": 0,
      "L5": 0,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0
    },
    "tip": "앞면을 모두 열고 양손 엄지만 막습니다. 첫 소리 내기에 가장 쉬운 음!",
    "flags": [],
    "ambiguousWith": [
      "highDo",
      "highDoS",
      "highRe",
      "highReS",
      "highMi"
    ]
  },
  {
    "id": "highDo",
    "solfege": "높은 도",
    "label": "높은 도",
    "pitch": "C6",
    "midi": 84,
    "breath": 4,
    "holes": {
      "L5": 0,
      "L4": 0,
      "L3": 0,
      "L2": 0,
      "LS": 0,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0,
      "RS": 0,
      "R1": 0,
      "L1": 1
    },
    "detectable": {
      "L2": 0,
      "L3": 0,
      "L4": 0,
      "L5": 0,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0
    },
    "tip": "오른손 엄지(RT)를 떼고 왼손 엄지만 막습니다.",
    "flags": [],
    "ambiguousWith": [
      "si",
      "highDoS",
      "highRe",
      "highReS",
      "highMi"
    ]
  },
  {
    "id": "highDoS",
    "solfege": "높은 도♯·레♭",
    "label": "높은 도#",
    "pitch": "C#6/Db6",
    "midi": 85,
    "breath": 4,
    "holes": {
      "L5": 0,
      "L4": 0,
      "L3": 0,
      "L2": 0,
      "LS": 0,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0,
      "RS": 0,
      "R1": 0,
      "L1": 0.5
    },
    "detectable": {
      "L2": 0,
      "L3": 0,
      "L4": 0,
      "L5": 0,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0
    },
    "tip": "왼손 엄지를 구멍에 반만 걸칩니다(반홀).",
    "flags": [
      "고급"
    ],
    "ambiguousWith": [
      "si",
      "highDo",
      "highRe",
      "highReS",
      "highMi"
    ]
  },
  {
    "id": "highRe",
    "solfege": "높은 레",
    "label": "높은 레",
    "pitch": "D6",
    "midi": 86,
    "breath": 5,
    "holes": {
      "L5": 0,
      "L4": 0,
      "L3": 0,
      "L2": 0,
      "LS": 0,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0,
      "RS": 0,
      "R1": 0,
      "L1": 0
    },
    "detectable": {
      "L2": 0,
      "L3": 0,
      "L4": 0,
      "L5": 0,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0
    },
    "tip": "모든 구멍을 엽니다. 엄지는 옆면을 받쳐 균형을 잡으세요.",
    "flags": [],
    "ambiguousWith": [
      "si",
      "highDo",
      "highDoS",
      "highReS",
      "highMi"
    ]
  },
  {
    "id": "highReS",
    "solfege": "높은 레♯·미♭",
    "label": "높은 레#",
    "pitch": "D#6/Eb6",
    "midi": 87,
    "breath": 5,
    "holes": {
      "L5": 0,
      "L4": 0,
      "L3": 0,
      "L2": 0,
      "LS": 0,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0,
      "RS": 0,
      "R1": 0,
      "L1": 0
    },
    "detectable": {
      "L2": 0,
      "L3": 0,
      "L4": 0,
      "L5": 0,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0
    },
    "tip": "전부 연 채로 입김을 더 빠르고 강하게. 악기별 편차가 큽니다.",
    "flags": [
      "고급"
    ],
    "ambiguousWith": [
      "si",
      "highDo",
      "highDoS",
      "highRe",
      "highMi"
    ]
  },
  {
    "id": "highMi",
    "solfege": "높은 미",
    "label": "높은 미",
    "pitch": "E6",
    "midi": 88,
    "breath": 5,
    "holes": {
      "L5": 0,
      "L4": 0,
      "L3": 0,
      "L2": 0,
      "LS": 0,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0,
      "RS": 0,
      "R1": 0,
      "L1": 0
    },
    "detectable": {
      "L2": 0,
      "L3": 0,
      "L4": 0,
      "L5": 0,
      "R2": 0,
      "R3": 0,
      "R4": 0,
      "R5": 0
    },
    "tip": "12공 최고 음역. 입김 각도를 살짝 올리고 빠른 호흡으로.",
    "flags": [
      "고급"
    ],
    "ambiguousWith": [
      "si",
      "highDo",
      "highDoS",
      "highRe",
      "highReS"
    ]
  }
];

export const MVP_NOTES = [
  "lowSi",
  "do",
  "doS",
  "re",
  "reS",
  "mi",
  "fa",
  "faS",
  "sol",
  "solS",
  "la",
  "laS"
];


export const OCARINA_TYPES = {
  hole12: {
    id: "hole12",
    name: "12홀 횡형",
    status: "ready",
    holes: HOLES_12,
    notes: NOTES_12,
    detectable: DETECTABLE_HOLES,
  },
  hole10: { id: "hole10", name: "10홀 횡형", status: "coming-soon", holes: [], notes: [], detectable: [] },
  hole6: { id: "hole6", name: "6홀 펜던트", status: "coming-soon", holes: [], notes: [], detectable: [] },
  hole4: { id: "hole4", name: "4홀 펜던트", status: "coming-soon", holes: [], notes: [], detectable: [] },
  double: { id: "double", name: "더블/트리플", status: "coming-soon", holes: [], notes: [], detectable: [] },
};

export function getNote(typeId, noteId) {
  const type = OCARINA_TYPES[typeId];
  if (!type) return undefined;
  return type.notes.find((note) => note.id === noteId);
}

export function getDetectableVector(note) {
  return Object.fromEntries(DETECTABLE_HOLES.map((holeId) => [holeId, note.holes[holeId]]));
}

export function getNoteLabel(noteId) {
  return NOTE_LABELS_KO[noteId] ?? noteId;
}
